spring:
  profiles:
    active: dev
---
server:
  port: 4001
spring:
  profiles:
    active: dev
  application:
    name: microservice-config-dev
---
server:
  port: 4002
spring:
     profiles:
       active: prod
     application:
       name: microservice-config-prod

